- set_fact:
    master_eip: "{{ hostvars[groups['master_nodes'][0]]['master_eip'] | default(False) }}"

- name: Register EIP for master nodes
  local_action:
    module: cs_ip_address
    zone: CH-GVA-2
  register: eip
  when: not master_eip

- set_fact:
    master_eip: "{{ hostvars[groups['master_nodes'][0]]['master_eip'] | default(eip.ip_address) }}"
