- set_fact:
    master_eip: "{{ hostvars[groups['master_nodes'][0]]['master_eip'] }}"

- file:
    path: /etc/kubernetes/manifests
    state: directory
    mode: 0644

- template:
    src: templates/haproxy.cfg.j2
    dest: /etc/kubernetes/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: docker restart haproxy

- template:
    src: templates/haproxy.j2
    dest: /etc/kubernetes/manifests/haproxy.yaml
    owner: root
    group: root
    mode: 0644

# kubernetes components
- template:
    src: templates/kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
    owner: root
    group: root
    mode: 0644
  notify: restart kubelet.service

- template:
    src: templates/kube_config.j2
    dest: /etc/kubernetes/kube_config.yaml
    owner: root
    group: root
    mode: 0644

- template:
    src: templates/kube_proxy.j2
    dest: /etc/kubernetes/manifests/kube_proxy.yaml
    owner: root
    group: root
    mode: 0644

- command: systemctl daemon-reload

- service:
    state: started
    enabled: yes
    name: kubelet
