- name: Check if Re-partition is needed
  raw: stat /dev/vda5
  register: need_partition
  ignore_errors: True

- name: Fix Partition
  shell: cgpt repair /dev/vda
  when: need_partition | failed

- name: Re-partition
  shell: parted /dev/vda print free | grep 'Free' | tail -1 | awk '{print $1 " " $2}' | xargs parted -a minimal --script /dev/vda 'mkpart HEKETI ext4'
  when: need_partition | failed

- name: Set boot partition
  shell: cgpt prioritize $(rootdev -s /usr)
  when: need_partition | failed

- name: Set successful flas
  shell: cgpt add -i 3 -S 1 /dev/vda
  when: need_partition | failed
