- name: Register EIP for worker nodes
  local_action:
    module: cs_ip_address
    zone: CH-GVA-2
  register: eip
  when: "'worker_nodes' not in groups or 'worker_eip' not in hostvars[groups['worker_nodes'][0]]"

- set_fact:
    worker_eip: "{{ hostvars[groups['worker_nodes'][0]]['worker_eip'] }}"
  when: "'skipped' in eip and eip['skipped']"

- set_fact:
    worker_eip: "{{ eip.ip_address }}"
  when: "'ip_address' in eip"
