- stat:
    path: /secret/cloudstack.ini
  register: csini

- set_fact:
    EXO_API_KEY: "{{ lookup('ini', 'key section=cloudstack file=/secret/cloudstack.ini') }}"
  when: "csini.stat.exists and csini.stat.isreg"

- set_fact:
    EXO_API_SECRET: "{{ lookup('ini', 'secret section=cloudstack file=/secret/cloudstack.ini') }}"
  when: "csini.stat.exists and csini.stat.isreg"

- set_fact:
    EXO_API_KEY: "{{ lookup('env', 'EXO_API_KEY') | default(EXO_API_KEY, true) }}"

- set_fact:
    EXO_API_SECRET: "{{ lookup('env', 'EXO_API_SECRET') | default(EXO_API_SECRET, true) }}"

- fail:
    msg: "Please set the EXO_API_KEY and EXO_API_SECRET environment variables. You can find these on your account page. https://portal.exoscale.ch/account/profile/api"
  when: not EXO_API_KEY and not EXO_API_SECRET

- set_fact:
    EXO_API_ENDPOINT: "{{ lookup('ini', 'endpoint section=cloudstack file=/secret/cloudstack.ini') }}"
  when: "csini.stat.exists and csini.stat.isreg"

- set_fact:
    EXO_API_ENDPOINT: "{{ lookup('env', 'EXO_API_ENDPOINT') | default(EXO_API_ENDPOINT, true) }}"

- name: write cloudstack.ini
  template:
    src: cloudstack_ini.j2
    dest: /secret/cloudstack.ini
